# Generated by Django 2.1 on 2018-08-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='campo_teste',
            field=models.CharField(max_length=100, null=True, verbose_name='Teste'),
        ),
    ]
