# Generated by Django 2.1 on 2018-08-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_campo_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='campo_teste',
        ),
    ]
